### ISSUE TITLE
音声変換時、行列次数が合わないエラーについてご質問させてください

### ISSUE THREAD

**Issue by YoshikazuOota** [Hiroshiba/yukarin#62]
お世話になっております。  
attic です。Issueの連投、恐縮です。

yukarin にて無事学習まで完了いたしましたが、音声変換時に下記の様なエラーが出てしまい、原因を特定できませんでした。  

```
IndexError: boolean index did not match indexed array along dimension 0; dimension is 580 but corresponding boolean dimension is 581
```

直接の原因は、```self.f0```・```self.sp```・```self.ap```の次数が、```index```の実数と一致しないことの様です。  
しかし、配列の次数が合わない原因までは特定できておりません。  
何か手がかりだけでも、ご教授いただければと思います。

**コマンド・エラーメッセージ**  
test_my_voiceに3つのファイルを置いて変換しようとした

```
attic@deeplearning:~/voice/yukarin$ python scripts/voice_change.py \
>     --voice_changer_model_dir './dat/1st_models/zun_voice_set/zun_model' \
>     --voice_changer_config './dat/1st_models/zun_voice_set/config.json' \
>     --voice_changer_model_iteration 60000 \
>     --super_resolution_model './dat/2nd_models/zun/predictor_140000.npz' \
>     --super_resolution_config './dat/2nd_models/zun/config.json' \
>     --input_statistics 'dat/1st_models/zun_voice_set/statistics/my.npy' \
>     --target_statistics 'dat/1st_models/zun_voice_set/statistics/zun.npy' \
>     --out_sampling_rate 41000 \
>     --dataset_target_wave_dir 'dat/voice_src/zun_voice_set/in_zunVoice_44100' \
>     --dataset_input_wave_dir 'dat/1st_models/zun_voice_set/out_myVoice_44100' \
>     --test_wave_dir './test_my_voice' \
>     --output_dir './output/' \
>     --gpu 0
Loaded acoustic converter model "dat/1st_models/zun_voice_set/zun_model/predictor_60000.npz"
Loaded super resolution model "dat/2nd_models/zun/predictor_140000.npz"
Traceback (most recent call last):
  File "scripts/voice_change.py", line 94, in process
    f_in_effective, effective = acoustic_converter.separate_effective(wave=w_in, feature=f_in, threshold=threshold)
  File "/home/attic/voice/yukarin/yukarin/acoustic_converter.py", line 82, in separate_effective
    feature = feature.indexing(effective)
  File "/home/attic/voice/yukarin/yukarin/acoustic_feature.py", line 86, in indexing
    f0=self.f0[index] if _is_target(self.f0) else numpy.nan,
IndexError: boolean index did not match indexed array along dimension 0; dimension is 580 but corresponding boolean dimension is 581
Traceback (most recent call last):
  File "scripts/voice_change.py", line 94, in process
    f_in_effective, effective = acoustic_converter.separate_effective(wave=w_in, feature=f_in, threshold=threshold)
  File "/home/attic/voice/yukarin/yukarin/acoustic_converter.py", line 82, in separate_effective
    feature = feature.indexing(effective)
  File "/home/attic/voice/yukarin/yukarin/acoustic_feature.py", line 86, in indexing
    f0=self.f0[index] if _is_target(self.f0) else numpy.nan,
IndexError: boolean index did not match indexed array along dimension 0; dimension is 1155 but corresponding boolean dimension is 1156
Traceback (most recent call last):
  File "scripts/voice_change.py", line 94, in process
    f_in_effective, effective = acoustic_converter.separate_effective(wave=w_in, feature=f_in, threshold=threshold)
  File "/home/attic/voice/yukarin/yukarin/acoustic_converter.py", line 82, in separate_effective
    feature = feature.indexing(effective)
  File "/home/attic/voice/yukarin/yukarin/acoustic_feature.py", line 86, in indexing
    f0=self.f0[index] if _is_target(self.f0) else numpy.nan,
IndexError: boolean index did not match indexed array along dimension 0; dimension is 1102 but corresponding boolean dimension is 1103
```

お手数ですが、よろしくお願いいたします！

**Comment by Hiroshiba** [comment]
サンプル数がFFTサイズで割り切れない場合に１ずれる問題が発生していました。
#63 で修正したので、最新版のコードなら動くと思います。

報告ありがとうございます。
またわからないことがあれば質問してください。

**Comment by YoshikazuOota** [comment]
深夜にも関わらず、ご対応ありがとうございます。
最新コミットを反映して試したところ、エラーは解消されました。
ありがとうございました！

**Comment by mizuka-ninomae** [comment]
同じような状況になりましたのでご報告します。
学習まで終了し、voice_change.pyを実行した所、エラーが発生しました。

最新のソースコードで実行
```
c:\yukarin>python scripts/voice_change.py --model_dir "model_stage1" --config_path "model_stage1\config.json" --input_statistics "input_statistics.npy" --target_statistics "target_statistics.npy" --output_sampling_rate 22050 --test_wave_dir "test_wav" --output_dir "output"
Loaded acoustic converter model "model_stage1\predictor_100000.npz"
Traceback (most recent call last):
  File "scripts/voice_change.py", line 75, in process
    f_in_effective, effective = acoustic_converter.separate_effective(wave=w_in, feature=f_in, threshold=threshold)
  File "c:\yukarin\yukarin\acoustic_converter.py", line 92, in separate_effective
    feature = feature.indexing(effective)
  File "c:\yukarin\yukarin\acoustic_feature.py", line 86, in indexing
    f0=self.f0[index] if _is_target(self.f0) else numpy.nan,
IndexError: boolean index did not match indexed array along dimension 0; dimension is 1347 but corresponding boolean dimension is 1350
```

念のため#63以前に戻して実行。
```
c:\yukarin>python scripts/voice_change.py --model_dir "model_stage1" --config_path "model_stage1\config.json" --input_statistics "input_statistics.npy" --target_statistics "target_statistics.npy" --output_sampling_rate 22050 --test_wave_dir "test_wav" --output_dir "output"
Loaded acoustic converter model "model_stage1\predictor_100000.npz"
Traceback (most recent call last):
  File "scripts/voice_change.py", line 75, in process
    f_in_effective, effective = acoustic_converter.separate_effective(wave=w_in, feature=f_in, threshold=threshold)
  File "c:\yukarin\yukarin\acoustic_converter.py", line 83, in separate_effective
    feature = feature.indexing(effective)
  File "c:\yukarin\yukarin\acoustic_feature.py", line 86, in indexing
    f0=self.f0[index] if _is_target(self.f0) else numpy.nan,
IndexError: boolean index did not match indexed array along dimension 0; dimension is 1347 but corresponding boolean dimension is 1351
```

対策等、ありましたらご教授お願い致します。
