### ISSUE TITLE
Test problem

### ISSUE THREAD

**Issue by daxian111** [Hiroshiba/yukarin#80]
Hi,sir.
I am puting the test input voice data in a directory , and run voice_change.py.
But the error is reported, the error message is as follows：

Traceback (most recent call last):
  File "voice_change.py", line 86, in process
    librosa.output.write_wav(y=wave.wave, path=str(output_dir / (p_in.stem + '.wav')), sr=wave.sampling_rate)
  File "/home/nikki_intern/anaconda3/envs/Yukarin/lib/python3.6/site-packages/librosa/output.py", line 225, in write_wav    util.valid_audio(y, mono=False)
  File "/home/nikki_intern/anaconda3/envs/Yukarin/lib/python3.6/site-packages/librosa/util/utils.py", line 170, in valid_audio
    raise ParameterError('Audio buffer is not finite everywhere')
librosa.util.exceptions.ParameterError: Audio buffer is not finite everywhere

I hope you can help me.

**Comment by Hiroshiba** [comment]
Maybe, generated wave data `wave.wave`  contain `numpy.inf` or `-numpy.inf`, because your trained model is not trained enough (or any bugs).
In this case, this problem will be solved by replacing `numpy.inf` to `0`.

For example: 
```python
wave.wave[~numpy.isfinite(wave.wave)] = 0
```
