### ISSUE TITLE
unsupported operand type(s) for /: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by Rose-sys** [Hiroshiba/yukarin#83]
Using voice_change with arguments:
```
python3 scripts/voice_change.py --model_dir './model_stage1' --config_path './model_stage1/config.json' --input_statistics '../../voice/input_statistics.npy' --target_statistics '../../voice/target_statistics.npy' --output_sampling_rate 24000 --disable_dataset_test --test_wave_dir '../../voice/tests/wav/' --output_dir '../../voice/tests/output/'
```
I keep getting the following error:
```
Traceback (most recent call last):
  File "scripts/voice_change.py", line 68, in process
    p_in = Path(glob.glob(str(dataset_wave_dir / p_in.stem) + '.*')[0])
TypeError: unsupported operand type(s) for /: 'NoneType' and 'str'
``` 

To what should I set --dataset_wave_dir? As it seems to try to load something from there, but that variable returns None.

```
<snip>
def process(p_in: Path, acoustic_converter: AcousticConverter):
    try:
        if p_in.suffix in ['.npy', '.npz']:
            print("p_in str: ", p_in)
            print("dataset_wave_dir str:", str(dataset_wave_dir))
            print("p_in.stem str:", str(p_in.stem))
            p_in = Path(glob.glob(str(dataset_wave_dir / p_in.stem) + '.*')[0])
<snip>
```
```
p_in str:  ../../voice/input_feature/3.npy
dataset_wave_dir str: None
p_in.stem str: 3
Traceback (most recent call last):
  File "scripts/voice_change.py", line 70, in process
    p_in = Path(glob.glob(str(dataset_wave_dir / p_in.stem) + '.*')[0])
TypeError: unsupported operand type(s) for /: 'NoneType' and 'str'
p_in str:  ../../voice/input_feature/1.npy
dataset_wave_dir str: None
p_in.stem str: 1
Traceback (most recent call last):
  File "scripts/voice_change.py", line 70, in process
    p_in = Path(glob.glob(str(dataset_wave_dir / p_in.stem) + '.*')[0])
TypeError: unsupported operand type(s) for /: 'NoneType' and 'str'
```

**Comment by Hiroshiba** [comment]
Set the path to the waves directory containing the `.wav` file.
I will close this issue, but please open it again if you have any problems.

**Comment by Rose-sys** [comment]
Thank you. 

I did that too, don't see any difference between the 2 except it converted some files from there (not all of it). Not sure if that is an issue. It was a minor thing since in the end it does what it should do :).

Anyway, hope to see some time some more documentation on the second stage training. It is quite confusing and a youtube tutorial that is relying only on become-yukarin only doesn't explain mean.npy and var.npy and how to get those for the first stage training. I suppose I should use this for first stage and become-yukarin for the second stage, reading your readme.

I'll figure it out eventually. Keep up the work 👍
