### ISSUE TITLE
最新の Linux バージョンでのインストール

### ISSUE THREAD

**Issue by SinisterSpatula** [Hiroshiba/yukarin#84]
私の翻訳をお許しください。 興味深いプロジェクトをインストールすることに非常に興味がありますが、2 年間で多くのことが変わりました。 ubunto 20 と cuda 11、465 ドライバー、および Titan X Pascal カードで動作しますか? cuda 10.1 および 418 ドライバーと 1060 カードが必要ですか? tensorflow 2.5.0 または 2.0 のみで動作しますか? python 3.6 と GCC 7 が必要ですか、それとも python 3.8 と GCC 8+ で動作しますか? 環境を正しく取得するのに非常に苦労しています。 アドバイスをいただければ幸いです。 まったくアップデートする予定はありますか？ ありがとうございました！

**Comment by SinisterSpatula** [comment]
I am getting much further with it now.  I learned about anaconda virtual environment for cuda apps which I found Extremely helpful for using old toolkit, python, gcc, etc.  I was able to do extract acoustics on my source wav file.  I guess it does not use GPU for that step.  Is that right?  When doing extract acoustics for my target it seemed to use a lot of cpu and ram but then became idle.  I let it run overnight about to see if it completed.  What is the best format for the input wav files?  I'm currently using 32-bit signed PCM at 24000hz sample rate.  I've been keeping them as one long 15 minute audio clip.  Is it better to divide into multiple small clips?

**Comment by ms903x1** [comment]
I'm sorry to intru。Can you train normally。I have the following problems. If you have the same problem and tell me the solution, thank you very much.

environment：wsl2-ubuntu20.4，cuda10.1 ,python3.6.6

Exception in main training loop: division by zero
Traceback (most recent call last):
  File "/home/ms903/anaconda3/envs/py36/lib/python3.6/site-packages/chainer/training/trainer.py", line 315, in run
    update()
  File "/home/ms903/anaconda3/envs/py36/lib/python3.6/site-packages/chainer/training/updaters/standard_updater.py", line 165, in update
    self.update_core()
  File "/home/ms903/Downloads/yukarin-master/yukarin/updater.py", line 87, in update_core
    batch = self.get_iterator('main').next()
  File "/home/ms903/anaconda3/envs/py36/lib/python3.6/site-packages/chainer/iterators/multiprocess_iterator.py", line 148, in __next__
    self.dataset_timeout)
  File "/home/ms903/anaconda3/envs/py36/lib/python3.6/site-packages/chainer/iterators/multiprocess_iterator.py", line 394, in measure
    indices = self._proceed()
  File "/home/ms903/anaconda3/envs/py36/lib/python3.6/site-packages/chainer/iterators/multiprocess_iterator.py", line 495, in _proceed
    previous_epoch_detail = epoch + pos / n
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "train.py", line 106, in <module>
    trainer.run()
  File "/home/ms903/anaconda3/envs/py36/lib/python3.6/site-packages/chainer/training/trainer.py", line 329, in run
    six.reraise(*sys.exc_info())
  File "/home/ms903/anaconda3/envs/py36/lib/python3.6/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/ms903/anaconda3/envs/py36/lib/python3.6/site-packages/chainer/training/trainer.py", line 315, in run
    update()
  File "/home/ms903/anaconda3/envs/py36/lib/python3.6/site-packages/chainer/training/updaters/standard_updater.py", line 165, in update
    self.update_core()
  File "/home/ms903/Downloads/yukarin-master/yukarin/updater.py", line 87, in update_core
    batch = self.get_iterator('main').next()
  File "/home/ms903/anaconda3/envs/py36/lib/python3.6/site-packages/chainer/iterators/multiprocess_iterator.py", line 148, in __next__
    self.dataset_timeout)
  File "/home/ms903/anaconda3/envs/py36/lib/python3.6/site-packages/chainer/iterators/multiprocess_iterator.py", line 394, in measure
    indices = self._proceed()
  File "/home/ms903/anaconda3/envs/py36/lib/python3.6/site-packages/chainer/iterators/multiprocess_iterator.py", line 495, in _proceed
    previous_epoch_detail = epoch + pos / n
ZeroDivisionError: division by zero
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:

**Comment by Hydroleo50** [comment]
To @SinisterSpatula :
> Is it better to divide into multiple small clips?

Sorry for a late answer, the code author has mentioned on other sites that splitting your audio files to <=15 second segments is helpful.

To @ms903x1 :
I also had this issue. It happened to be an incompatibility issue between modules. I am being more successful with cuda 10.0 and following module versions:

- chainer==6.0.0
- cupy==6.0.0
- numba==0.48.0
- librosa==0.6.3
- pyworld==0.3.0
- matplotlib==3.5.3
- tensorflow- Not sure yet
- pysptk==0.1.21
- tqdm==4.64.0
- tensorboard-chainer- Still experimenting with that

I still haven't been able to get train.py to run properly, but with these i have made it further than ever before. I will update if i discover anything new. Hopefully i could help.

**Comment by SinisterSpatula** [comment]
Yes I did end up dividing the audio into many small clips and that worked better for me.  The problem with this model is that it requires a vast amount of parallel audio clips.  So far the most I have tried is one hour and a half worth of clips and the quality still wasn't what I hoped for.  I'm sure with more clips it will sound better but I dont have the time a patience require to build the vast parallel data set.
